services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - db

  api:
    ports:
      - "3000"

  db:
    ports:
      - "5432"
