create schema uis;

create table uis.species (
  id integer generated by default as identity primary key,
  name text not null,
  commonNames text[] not null
);

insert into uis.species (name, commonNames) values
  ('Blighia Sapida', '{Akee}'),
  ('Syzgium Malaccense', '{Jamaican Apple}'),
  ('Diospyros Nigra', '{Black Sapote}'),
  ('Cocos Nucifera', '{Coconut}'),
  ('Artocarpus Heterophyllus', '{Jackfruit}'),
  ('Averrhoa Carambola', '{Starfruit}'),
  ('Inga Edulis', '{Regular Ice Cream Bean, Dwarf Ice Cream Bean}'),
  ('Nephelium Lappaceum', '{Rambutan}'),
  ('Pouteria Caimito', '{Abiu}');

create type uis.coordinates as (
  lat decimal(8,6),
  lng decimal(9,6)
);

create table uis.plants (
  id integer generated by default as identity primary key,
  species integer not null references uis.species(id),
  location uis.coordinates not null,
  created_time timestamptz not null
);

insert into uis.plants (species, location, created_time) values
  (1, row(43, 16), '2016-06-22 19:10:25-07');

create role uis_anon nologin;

grant usage on schema uis to uis_anon;
grant select, insert on uis.plants to uis_anon;
grant select, insert on uis.species to uis_anon;
